name: workflow2
on : push
jobs:
  lint-job:
  runs-on: ubuntu_latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - name : dependency
        run : npm ci
      - name : lint
        run : npm run lint
  test-job:
  runs-on: ubuntu_latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - name : dependency
        run : npm ci
      - name : test
        run : npm run test
  build-job:
  runs-on: ubuntu_latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - name : dependency
        run : npm ci
      - name : build
        run : npm run build
      - name : deploy
        run : echo "Deploying code.."
    
    
    
    


